[project]
name = "pepycli"
version = "0.1.0"
description = "CLI Util for get analytics from pepy.tech"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.15",
    "python-dotenv>=1.1.1",
    "typer>=0.16.1",
]

[project.scripts]
pepycli = "pepycli.cli:main"